[package]
name = "avro-to-json"
version = "0.1.0"
edition = "2021"

[lib]
name = "avro_to_json"

[[bin]]
name = "avro-to-json"
path = "src/main.rs"

[dependencies]
apache-avro = { version = "0.16", features = ["snappy", "zstandard", "bzip", "xz"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
colored = "2.0"
